version: "3.9"
    
services:
  db:
    image: mariadb:10.5
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MS_PASS}
      MYSQL_DATABASE: ${MS_DB}
      MYSQL_USER: ${MS_USER}
      MYSQL_PASSWORD: ${MS_USER_PASS}

  wordpress:
    depends_on:
      - db
    image: wordpress:5.7.2
    volumes:
      - ./wp-content:/var/www/html/wp-content
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${WP_USER}
      WORDPRESS_DB_PASSWORD: ${WP_PASS}
      WORDPRESS_DB_NAME: ${WP_DB_NAME}
volumes:
  db_data: {}